services:
  db:
    image: mysql:8
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: faciltrack
      MYSQL_USER: faciltrack
      MYSQL_PASSWORD: faciltrack
    ports:
      - "3307:3306"
    volumes:
      - mysqldata:/var/lib/mysql

volumes:
  mysqldata:
